version: '3'

services:
  api:
    container_name: evolution_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - ${API_PORT:-5858}:5858
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 5858
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5858/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    restart: always
    command: >
      redis-server 
      --port 6379 
      --appendonly yes
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - evolution_redis:/data
    ports:
      - ${REDIS_PORT:-6378}:6379

  nginx-failover:
    image: nginx:latest
    container_name: nginx_failover
    restart: always
    ports:
      - "9080:80"  # Alternative port for failover
      - "9443:443" # Alternative SSL port for failover
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/usr/share/nginx/html
    networks:
      - evolution-net
    depends_on:
      - api

  domain-watcher:
    image: alpine:latest
    container_name: domain_watcher
    restart: always
    volumes:
      - ./scripts:/scripts
    networks:
      - evolution-net
    entrypoint: /bin/sh
    command: -c "apk add --no-cache curl bind-tools && chmod +x /scripts/check_domain.sh && /scripts/check_domain.sh"
    depends_on:
      - api
      - nginx-failover

volumes:
  evolution_instances:
  evolution_redis:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge