services:
  api:
    container_name: evolution_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - ${API_PORT:-5858}:5858
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 5858
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5858/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - traefik.http.services.api.loadbalancer.server.port=5858
      - traefik.http.routers.api.service=api
      - traefik.http.routers.api.rule=Host(`wa.ruut.chat`)
      - traefik.http.routers.api.timeout.read=120s 

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server 
      --port 6379 
      --appendonly yes
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - evolution_redis:/data
    ports:
      - ${REDIS_PORT:-6378}:6379

volumes:
  evolution_instances:
  evolution_redis:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge